# Generated by Django 2.0.2 on 2018-02-23 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo_especialistas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadanía'), ('CE', 'Cédula Extrangería'), ('PS', 'Pasaporte'), ('TI', 'Tarjeta Identidad')], default='CC', max_length=2)),
                ('nro_identificacion', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('nombre_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('apellido', models.CharField(max_length=60)),
                ('apellido_segundo', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=20)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=60, null=True)),
                ('universidad', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('firma', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.Especialidad', verbose_name='Especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especialista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoRemitente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
                ('especialidad_temporal', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_1', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono_2', models.CharField(blank=True, max_length=120, null=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medicos.Especialidad', verbose_name='Especialidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
