# Generated by Django 2.0.2 on 2018-02-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicoremitente',
            name='especialidad_temporal',
        ),
        migrations.RemoveField(
            model_name='medicoremitente',
            name='telefono_1',
        ),
        migrations.RemoveField(
            model_name='medicoremitente',
            name='telefono_2',
        ),
    ]
