# Generated by Django 2.0.2 on 2018-02-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20180224_0326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'permissions': (('list_especialidad', 'Can list especialidades'), ('detail_especialidad', 'Can detail especialidad'))},
        ),
        migrations.AlterModelOptions(
            name='medicoremitente',
            options={'permissions': (('list_medicoremitente', 'Can list medicos remitentes'), ('detail_medicoremitente', 'Can detail medico remitente'))},
        ),
    ]
