# Generated by Django 2.0.2 on 2018-03-03 05:36

from django.db import migrations
import imagekit.models.fields
import medicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_auto_20180227_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='firma',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=medicos.models.Especialista.firma_upload_to),
        ),
    ]
