# Generated by Django 2.0.2 on 2018-04-28 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0005_auto_20180306_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('A1_1', models.BooleanField(default=0, verbose_name='Satisfactoria para evaluación')),
                ('A1_1a', models.BooleanField(default=0, verbose_name='Con presencia de células endocervicales')),
                ('A1_1b', models.BooleanField(default=0, verbose_name='Sin presencia de células endocervicales')),
                ('A1_2', models.BooleanField(default=0, verbose_name='Insactisfactoria para evaluación')),
                ('A1_i', models.BooleanField(default=0, verbose_name='Exudado inflamatorio')),
                ('A1_ii', models.BooleanField(default=0, verbose_name='Hemorragia')),
                ('A1_iii', models.BooleanField(default=0, verbose_name='Citolisis')),
                ('A1_iv', models.BooleanField(default=0, verbose_name='Extendido Grueso')),
                ('A1_v', models.BooleanField(default=0, verbose_name='Mala preservación/fijación')),
                ('A1_vi', models.BooleanField(default=0, verbose_name='Escasa Celularidad')),
                ('A1_vii', models.BooleanField(default=0, verbose_name='Datos Clínicos Insuficientes')),
                ('A3', models.BooleanField(default=0, verbose_name='Muestra no evaluada por')),
                ('A3a', models.BooleanField(default=0, verbose_name='Ruptura de la placa que hace imposible la reparación')),
                ('A3b', models.BooleanField(default=0, verbose_name='Ausencia de Identificación')),
                ('B1', models.BooleanField(default=0, verbose_name='Negativa para lesión intraepitelial o malignidad')),
                ('B1a', models.BooleanField(default=0, verbose_name='Con cambios celulares reactivos asociados a')),
                ('B1a_i', models.BooleanField(default=0, verbose_name='Inflamación')),
                ('B1a_ii', models.BooleanField(default=0, verbose_name='Irradiación')),
                ('B1a_iii', models.BooleanField(default=0, verbose_name='Dispositivo Intrauterino')),
                ('B1a_iv', models.BooleanField(default=0, verbose_name='Reparación')),
                ('B1b', models.BooleanField(default=0, verbose_name='Con Cambios por Atrofia')),
                ('B1c', models.BooleanField(default=0, verbose_name='Con Células glandulares benignas post-histerectomía')),
                ('B1d', models.BooleanField(default=0, verbose_name='Con presencia de células endometriales fuera de fase')),
                ('B2', models.BooleanField(default=0, verbose_name='Anormalidad en células epiteliales escamosas')),
                ('B2a', models.BooleanField(default=0, verbose_name='De significado indeterminado (ASC-US)')),
                ('B2b', models.BooleanField(default=0, verbose_name='Que no permite excluir lesión intraepitelial de alto grado')),
                ('B3', models.BooleanField(default=0, verbose_name='Lesión escamosa epitelial de bajo grado')),
                ('B3a', models.BooleanField(default=0, verbose_name='Incluye cambios por VPH')),
                ('B4', models.BooleanField(default=0, verbose_name='Lesión escamosa epitelial de alto grado')),
                ('B5', models.BooleanField(default=0, verbose_name='Carcinoma escamocelular')),
                ('B6', models.BooleanField(default=0, verbose_name='Anormalidades en')),
                ('B6a', models.BooleanField(default=0, verbose_name='Células epiteliales')),
                ('B6a_i', models.BooleanField(default=0, verbose_name='Endocervicales sin ninguna otra especificación')),
                ('B6a_ii', models.BooleanField(default=0, verbose_name='Endometriales sin ninguna otra especificación')),
                ('B7', models.BooleanField(default=0, verbose_name='Adenocarcinoma endocervical in situ')),
                ('B8', models.BooleanField(default=0, verbose_name='Adenocarcinoma')),
                ('B8a', models.BooleanField(default=0, verbose_name='Endocervical')),
                ('B8b', models.BooleanField(default=0, verbose_name='Endometrial')),
                ('B8c', models.BooleanField(default=0, verbose_name='Extrauterino')),
                ('B8d', models.BooleanField(default=0, verbose_name='De sitio no especificado')),
                ('B9', models.BooleanField(default=0, verbose_name='Otra Neoplastia Maligna')),
                ('C1', models.BooleanField(default=0, verbose_name='No se observan microorganismos patógenos')),
                ('C2', models.BooleanField(default=0, verbose_name='Bacterias morfológicamente consistentes con actinomyces')),
                ('C3', models.BooleanField(default=0, verbose_name='Desviación de la flora sugestiva de vaginosis bacteriana')),
                ('C4', models.BooleanField(default=0, verbose_name='Trichonomas vaginalis')),
                ('C5', models.BooleanField(default=0, verbose_name='Hongos mofológicamente compatibles con Candida Sp')),
                ('C6', models.BooleanField(default=0, verbose_name='Cambios citopáticos asociados a Herpes')),
                ('C7', models.BooleanField(default=0, verbose_name='No se observan microorganismos')),
                ('orden_examen', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='citología', to='ordenes.OrdenExamen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
