# Generated by Django 2.0.2 on 2018-04-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citologia',
            name='orden_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='citologia', to='ordenes.OrdenExamen'),
        ),
    ]
