# Generated by Django 2.0.2 on 2018-05-19 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20180306_1804'),
        ('examenes_especiales', '0002_auto_20180428_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biopsia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('descripcion_macroscopica', models.TextField(blank=True, null=True)),
                ('descripcion_microscopica', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('orden_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biopsia', to='ordenes.OrdenExamen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='citologia',
            name='orden_examen',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citologia', to='ordenes.OrdenExamen'),
        ),
    ]
