# Generated by Django 2.0.2 on 2018-05-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0004_auto_20180519_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='citologia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
