# Generated by Django 2.0.2 on 2018-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0005_citologia_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsia',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
