# Generated by Django 2.0.2 on 2018-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0006_biopsia_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsia',
            name='nro_examen_especial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citologia',
            name='nro_examen_especial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
