# Generated by Django 2.0.2 on 2018-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0007_auto_20180521_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsia',
            name='descripcion_macroscopica',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Macroscópica'),
        ),
        migrations.AlterField(
            model_name='biopsia',
            name='descripcion_microscopica',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Microscópica'),
        ),
        migrations.AlterField(
            model_name='biopsia',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnóstico'),
        ),
    ]
