# Generated by Django 2.0.2 on 2018-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0008_auto_20180616_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biopsia',
            name='nro_examen_especial',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citologia',
            name='nro_examen_especial',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
