# Generated by Django 2.0.2 on 2018-08-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes_especiales', '0009_auto_20180804_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='biopsia',
            name='nombre',
            field=models.CharField(default='Informe Patología', max_length=300),
        ),
    ]
