branch-defaults:
  master:
    environment: labclinico
global:
  application_name: labcollazos
  branch: null
  default_ec2_keyname: eb-lab
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: labcollazos
  repository: null
  sc: git
  workspace_type: Application
