# Generated by Django 2.0.2 on 2018-02-24 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0005_auto_20180223_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEntidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('enviar_correo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto Entidad',
                'verbose_name_plural': 'Contactos Entidad',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('nit', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='EntidadExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_examen', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes', to='entidades.Entidad')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_entidades', to='examenes.Examen')),
            ],
        ),
        migrations.AddField(
            model_name='entidad',
            name='examenes',
            field=models.ManyToManyField(through='entidades.EntidadExamen', to='examenes.Examen'),
        ),
        migrations.AddField(
            model_name='contactoentidad',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_contactos', to='entidades.Entidad'),
        ),
    ]
