# Generated by Django 2.0.2 on 2018-02-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_auto_20180224_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactoentidad',
            options={'permissions': (('list_contactoentidad', 'Can list contactos entidades'), ('detail_contactoentidad', 'Can detail contacto entidad')), 'verbose_name': 'Contacto Entidad', 'verbose_name_plural': 'Contactos Entidad'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'permissions': (('list_entidad', 'Can list entidades'), ('detail_entidad', 'Can detail entidad')), 'verbose_name': 'Entidad', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='entidadexamen',
            options={'permissions': (('list_examen', 'Can list examenes'), ('detail_examen', 'Can detail examen'))},
        ),
    ]
