# Generated by Django 2.0.2 on 2018-02-24 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entidades', '0003_auto_20180224_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mi_entidad', to=settings.AUTH_USER_MODEL),
        ),
    ]
