# Generated by Django 2.0.2 on 2018-02-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CupsGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cups Grupo',
                'verbose_name_plural': 'Cups Grupos',
            },
        ),
        migrations.CreateModel(
            name='CupsSubGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_subgrupos', to='examenes.CupsGrupo')),
            ],
            options={
                'verbose_name': 'Cups Sub Grupo',
                'verbose_name_plural': 'Cups Sub Grupos',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cups', models.PositiveIntegerField(help_text='Código de clasificación única en procedimientos en salud', unique=True)),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombre del Examen')),
                ('nombre_corto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Examen (Corto)')),
                ('valor_referencia', models.TextField(blank=True, null=True, verbose_name='Valor de Referencia')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('tecnica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnica')),
                ('costo_referencia', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Costo Referencia del Examen')),
                ('multifirma', models.BooleanField(default=False, verbose_name='Multiple Firma')),
                ('especial', models.BooleanField(default=False, verbose_name='Plantilla Especial')),
                ('nro_plantilla', models.PositiveIntegerField(blank=True, choices=[(1, 'Biopsia'), (2, 'Citología')], null=True, verbose_name='Nro. Plantilla Especial')),
                ('subgrupo_cups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes', to='examenes.CupsSubGrupo')),
            ],
            options={
                'verbose_name': 'Exámen',
                'verbose_name_plural': 'Examenes',
            },
        ),
    ]
