# Generated by Django 2.0.2 on 2018-02-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupsgrupo',
            options={'permissions': (('list_cupsgrupo', 'Can list grupos cups'), ('detail_cupsgrupo', 'Can detail grupos cups')), 'verbose_name': 'Cups Grupo', 'verbose_name_plural': 'Cups Grupos'},
        ),
    ]
