# Generated by Django 2.0.2 on 2018-02-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_auto_20180221_0413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupssubgrupo',
            options={'permissions': (('list_cupssubgrupo', 'Can list sub grupos cups'), ('detail_cupssubgrupo', 'Can detail sub grupos cups')), 'verbose_name': 'Cups Sub Grupo', 'verbose_name_plural': 'Cups Sub Grupos'},
        ),
    ]
