# Generated by Django 2.0.2 on 2018-02-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_auto_20180221_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'permissions': (('list_examen', 'Can list examen'), ('detail_examen', 'Can detail examen')), 'verbose_name': 'Exámen', 'verbose_name_plural': 'Examenes'},
        ),
    ]
