# Generated by Django 2.0.2 on 2018-02-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_auto_20180222_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupsgrupo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='cupssubgrupo',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='nombre',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre del Examen'),
        ),
    ]
