# Generated by Django 2.0.2 on 2018-06-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_examen_no_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='no_email',
            field=models.BooleanField(default=False),
        ),
    ]
