# Generated by Django 2.0.2 on 2018-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_auto_20180616_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='codigo_cups',
            field=models.CharField(help_text='Código de clasificación única en procedimientos en salud', max_length=10, unique=True),
        ),
    ]
