# Generated by Django 2.0.2 on 2018-06-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_auto_20180623_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='costo_referencia',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='Costo Referencia del Examen'),
        ),
    ]
