# Generated by Django 2.0.2 on 2018-03-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'permissions': [('list_orden', 'Can list Ordenes'), ('detail_orden', 'Can see Orden')]},
        ),
    ]
