# Generated by Django 2.0.2 on 2018-03-05 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examenes', '0005_auto_20180223_0002'),
        ('ordenes', '0002_auto_20180304_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('examen_estado', models.PositiveIntegerField(choices=[(0, 'En Proceso'), (1, 'Con Resultados'), (2, 'Verificado'), (3, 'Impreso')], default=0)),
                ('tecnica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnica')),
                ('examen_valor_referencia', models.TextField(blank=True, null=True, verbose_name='Valor de Referencia')),
                ('especial', models.BooleanField(default=False, verbose_name='Plantilla Especial')),
                ('nro_plantilla', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nro. Plantilla Especial')),
                ('paciente_nombre', models.CharField(max_length=200)),
                ('examen_nombre', models.CharField(max_length=300, verbose_name='Nombre del Examen')),
                ('examen_codigo_cups', models.PositiveIntegerField(help_text='Código de clasificación única en procedimientos en salud')),
                ('examen_unidad_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('resultado', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('descuento', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('valor_total', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Total')),
                ('valor_descuento', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Descuento')),
                ('valor_final', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Valor Final')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes_creados', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='examenes.Examen')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes_modificados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mis_examenes', to='ordenes.Orden')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='examenes',
            field=models.ManyToManyField(related_name='mis_examenes', through='ordenes.OrdenExamen', to='examenes.Examen'),
        ),
    ]
