# Generated by Django 2.0.2 on 2018-03-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_ordenexamenfirmas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenexamen',
            options={'permissions': [('list_pendientes_ordenexamen', 'Can list orden examen pendientes'), ('list_con_resultados_ordenexamen', 'Can list orden examen con resultados'), ('list_verificados_ordenexamen', 'Can list orden examen verificados'), ('firmar_como_ordenexamen', 'Can firmar como orden examen'), ('verificar_ordenexamen', 'Can verificar orden examen')]},
        ),
    ]
