# Generated by Django 2.0.2 on 2018-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_auto_20180306_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='nro_examen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
