# Generated by Django 2.0.2 on 2018-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_ordenexamen_nro_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenexamen',
            name='nro_examen',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
