# Generated by Django 2.0.2 on 2018-07-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_auto_20180521_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nro_orden',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='tipo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('RELACION DE COBRO', 'Relación de Cobro'), ('CORTESIA', 'Cortesía')], default='EFECTIVO', max_length=30),
        ),
    ]
