# Generated by Django 2.0.2 on 2018-07-24 03:20

from django.db import migrations, models
import ordenes.models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_ordenexamen_pdf_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='pdf_examen_encriptado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordenexamen',
            name='pdf_examen',
            field=models.FileField(blank=True, null=True, upload_to=ordenes.models.OrdenExamen.examen_upload_to),
        ),
    ]
