# Generated by Django 2.0.2 on 2018-07-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_auto_20180723_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='fecha_verificado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
