# Generated by Django 2.0.2 on 2018-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_ordenexamen_cargue_sin_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
