# Generated by Django 2.0.2 on 2018-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_auto_20180825_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='nro_orden',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
