# Generated by Django 2.0.2 on 2018-10-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_auto_20180901_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
