# Generated by Django 2.0.2 on 2018-10-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0018_auto_20181001_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_ingreso',
            field=models.DateTimeField(null=True),
        ),
    ]
