# Generated by Django 2.0.2 on 2018-10-08 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0020_auto_20181001_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_ingreso',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 18, 19, 17, 839114, tzinfo=utc), null=True),
        ),
    ]
