# Generated by Django 2.0.2 on 2018-10-08 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0021_auto_20181008_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
